tinymce.addI18n("bg_BG", {

	// Символы
	"100": "100",
	"1234": "1234",
	"heart": "heart",
	"orange_heart": "orange heart",
	"yellow_heart": "yellow heart",
	"green_heart": "green heart",
	"blue_heart": "blue heart",
	"purple_heart": "purple heart",
	"black_heart": "black heart",
	"broken_heart": "broken heart",
	"heavy_heart_exclamation": "heavy heart exclamation",
	"two_hearts": "two hearts",
	"revolving_hearts": "revolving hearts",
	"heartbeat": "heartbeat",
	"heartpulse": "heartpulse",
	"sparkling_heart": "sparkling heart",
	"cupid": "cupid",
	"gift_heart": "gift heart",
	"heart_decoration": "heart decoration",
	"peace_symbol": "peace symbol",
	"latin_cross": "latin cross",
	"star_and_crescent": "star and crescent",
	"om": "om",
	"wheel_of_dharma": "wheel of dharma",
	"star_of_david": "star of david",
	"six_pointed_star": "six pointed star",
	"menorah": "menorah",
	"yin_yang": "yin yang",
	"orthodox_cross": "orthodox cross",
	"place_of_worship": "place of worship",
	"ophiuchus": "ophiuchus",
	"aries": "aries",
	"taurus": "taurus",
	"gemini": "gemini",
	"cancer": "cancer",
	"leo": "leo",
	"virgo": "virgo",
	"libra": "libra",
	"scorpius": "scorpius",
	"sagittarius": "sagittarius",
	"capricorn": "capricorn",
	"aquarius": "aquarius",
	"pisces": "pisces",
	"ID": "ID",
	"atom_symbol": "atom symbol",
	"u7a7a": "u7a7a",
	"u5272": "u5272",
	"radioactive": "radioactive",
	"biohazard": "biohazard",
	"mobile_phone_off": "mobile phone off",
	"vibration_mode": "vibration mode",
	"u6709": "u6709",
	"u7121": "u7121",
	"u7533": "u7533",
	"u55b6": "u55b6",
	"u6708": "u6708",
	"eight_pointed_black_star": "eight pointed black star",
	"vs": "vs",
	"accept": "accept",
	"white_flower": "white flower",
	"ideograph_advantage": "ideograph advantage",
	"secret": "secret",
	"congratulations": "congratulations",
	"u5408": "u5408",
	"u6e80": "u6e80",
	"u7981": "u7981",
	"a": "a",
	"B": "B",
	"ab": "ab",
	"cl": "cl",
	"o2": "o2",
	"sos": "sos",
	"no_entry": "no entry",
	"name_badge": "name badge",
	"no_entry_sign": "no entry sign",
	"x": "x",
	"o": "o",
	"stop_sign": "stop sign",
	"anger": "anger",
	"hotsprings": "hotsprings",
	"no_pedestrians": "no pedestrians",
	"do_not_litter": "do not litter",
	"no_bicycles": "no bicycles",
	"non_potable_water": "non potable water",
	"underage": "underage",
	"no_mobile_phones": "no mobile phones",
	"exclamation": "exclamation",
	"grey_exclamation": "grey exclamation",
	"question": "question",
	"grey_question": "grey question",
	"bangbang": "bangbang",
	"interrobang": "interrobang",
	"low_brightness": "low brightness",
	"high_brightness": "high brightness",
	"trident": "trident",
	"fleur_de_lis": "fleur de lis",
	"part_alternation_mark": "part alternation mark",
	"warning": "warning",
	"children_crossing": "children crossing",
	"beginner": "beginner",
	"recycle": "recycle",
	"u6307": "u6307",
	"chart": "chart",
	"sparkle": "sparkle",
	"eight_spoked_asterisk": "eight spoked asterisk",
	"negative_squared_cross_mark": "negative squared cross mark",
	"white_check_mark": "white check mark",
	"diamond_shape_with_a_dot_inside": "diamond shape with a dot inside",
	"cyclone": "cyclone",
	"loop": "loop",
	"globe_with_meridians": "globe with meridians",
	"m": "m",
	"atm": "atm",
	"sa": "sa",
	"passport_control": "passport control",
	"customs": "customs",
	"baggage_claim": "baggage claim",
	"left_luggage": "left luggage",
	"wheelchair": "wheelchair",
	"no_smoking": "no smoking",
	"wc": "wc",
	"parking": "parking",
	"potable_water": "potable water",
	"mens": "mens",
	"womens": "womens",
	"baby_symbol": "baby symbol",
	"restroom": "restroom",
	"put_litter_in_its_place": "put litter in its place",
	"cinema": "cinema",
	"signal_strength": "signal strength",
	"koko": "koko",
	"ng": "ng",
	"up": "up",
	"cool": "cool",
	"new": "new",
	"free": "free",
	"zero": "zero",
	"one": "one",
	"two": "two",
	"three": "three",
	"four": "four",
	"five": "five",
	"six": "six",
	"seven": "seven",
	"eight": "eight",
	"nine": "nine",
	"keycap_ten": "keycap ten",
	"asterisk": "asterisk",
	"eject_button": "eject button",
	"arrow_forward": "arrow forward",
	"pause_button": "pause button",
	"next_track_button": "next track button",
	"stop_button": "stop button",
	"record_button": "record button",
	"play_or_pause_button": "play or pause button",
	"previous_track_button": "previous track button",
	"fast_forward": "fast forward",
	"rewind": "rewind",
	"twisted_rightwards_arrows": "twisted rightwards arrows",
	"repeat": "repeat",
	"repeat_one": "repeat one",
	"arrow_backward": "arrow backward",
	"arrow_up_small": "arrow up small",
	"arrow_down_small": "arrow down small",
	"arrow_double_up": "arrow double up",
	"arrow_double_down": "arrow double down",
	"arrow_right": "arrow right",
	"arrow_left": "arrow left",
	"arrow_up": "arrow up",
	"arrow_down": "arrow down",
	"arrow_upper_right": "arrow upper right",
	"arrow_lower_right": "arrow lower right",
	"arrow_lower_left": "arrow lower left",
	"arrow_upper_left": "arrow upper left",
	"arrow_up_down": "arrow up down",
	"left_right_arrow": "left right arrow",
	"arrows_counterclockwise": "arrows counterclockwise",
	"arrow_right_hook": "arrow right hook",
	"leftwards_arrow_with_hook": "leftwards arrow with hook",
	"arrow_heading_up": "arrow heading up",
	"arrow_heading_down": "arrow heading down",
	"hash": "hash",
	"information_source": "information source",
	"abc": "abc",
	"abcd": "abcd",
	"capital_abcd": "capital abcd",
	"musical_note": "musical note",
	"notes": "notes",
	"wavy_dash": "wavy dash",
	"curly_loop": "curly loop",
	"heavy_check_mark": "heavy check mark",
	"arrows_clockwise": "arrows clockwise",
	"heavy_plus_sign": "heavy plus sign",
	"heavy_minus_sign": "heavy minus sign",
	"heavy_division_sign": "heavy division sign",
	"heavy_multiplication_x": "heavy multiplication x",
	"infinity": "infinity",
	"heavy_dollar_sign": "heavy dollar sign",
	"currency_exchange": "currency exchange",
	"copyright": "copyright",
	"registered": "registered",
	"tm": "tm",
	"end": "end",
	"back": "back",
	"on": "on",
	"soon": "soon",
	"ballot_box_with_check": "ballot box with check",
	"radio_button": "radio button",
	"white_circle": "white circle",
	"black_circle": "black circle",
	"red_circle": "red circle",
	"large_blue_circle": "large blue circle",
	"small_orange_diamond": "small orange diamond",
	"small_blue_diamond": "small blue diamond",
	"large_orange_diamond": "large orange diamond",
	"large_blue_diamond": "large blue diamond",
	"small_red_triangle": "small red triangle",
	"black_small_square": "black small square",
	"white_small_square": "white small square",
	"black_large_square": "black large square",
	"white_large_square": "white large square",
	"small_red_triangle_down": "small red triangle down",
	"black_medium_square": "black medium square",
	"white_medium_square": "white medium square",
	"black_medium_small_square": "black medium small square",
	"white_medium_small_square": "white medium small square",
	"black_square_button": "black square button",
	"white_square_button": "white square button",
	"speaker": "speaker",
	"sound": "sound",
	"loud_sound": "loud sound",
	"mute": "mute",
	"mega": "mega",
	"loudspeaker": "loudspeaker",
	"bell": "bell",
	"no_bell": "no bell",
	"black_joker": "black joker",
	"mahjong": "mahjong",
	"spades": "spades",
	"clubs": "clubs",
	"hearts": "hearts",
	"diamonds": "diamonds",
	"flower_playing_cards": "flower playing cards",
	"thought_balloon": "thought balloon",
	"right_anger_bubble": "right anger bubble",
	"speech_balloon": "speech balloon",
	"left_speech_bubble": "left speech bubble",
	"clock1": "clock1",
	"clock2": "clock2",
	"clock3": "clock3",
	"clock4": "clock4",
	"clock5": "clock5",
	"clock6": "clock6",
	"clock7": "clock7",
	"clock8": "clock8",
	"clock9": "clock9",
	"clock10": "clock10",
	"clock11": "clock11",
	"clock12": "clock12",
	"clock130": "clock130",
	"clock230": "clock230",
	"clock330": "clock330",
	"clock430": "clock430",
	"clock530": "clock530",
	"clock630": "clock630",
	"clock730": "clock730",
	"clock830": "clock830",
	"clock930": "clock930",
	"clock1030": "clock1030",
	"clock1130": "clock1130",
	"clock1230": "clock1230",

	// Люди
	"grinning": "grinning",
	"grimacing": "grimacing",
	"grin": "grin",
	"joy": "joy",
	"rofl": "rofl",
	"partying": "partying",
	"smiley": "smiley",
	"smile": "smile",
	"sweat_smile": "sweat smile",
	"laughing": "laughing",
	"innocent": "innocent",
	"wink": "wink",
	"blush": "blush",
	"slightly_smiling_face": "slightly smiling face",
	"upside_down_face": "upside down face",
	"relaxed": "relaxed",
	"yum": "yum",
	"relieved": "relieved",
	"heart_eyes": "heart eyes",
	"smiling_face_with_three_hearts": "smiling face with three hearts",
	"kissing_heart": "kissing heart",
	"kissing": "kissing",
	"kissing_smiling_eyes": "kissing smiling eyes",
	"kissing_closed_eyes": "kissing closed eyes",
	"stuck_out_tongue_winking_eye": "stuck out tongue winking eye",
	"zany": "zany",
	"raised_eyebrow": "raised eyebrow",
	"monocle": "monocle",
	"stuck_out_tongue_closed_eyes": "stuck out tongue closed eyes",
	"stuck_out_tongue": "stuck out tongue",
	"money_mouth_face": "money mouth face",
	"nerd_face": "nerd face",
	"sunglasses": "sunglasses",
	"star_struck": "star struck",
	"clown_face": "clown face",
	"cowboy_hat_face": "cowboy hat face",
	"hugs": "hugs",
	"smirk": "smirk",
	"no_mouth": "no mouth",
	"neutral_face": "neutral face",
	"expressionless": "expressionless",
	"unamused": "unamused",
	"roll_eyes": "roll eyes",
	"thinking": "thinking",
	"lying_face": "lying face",
	"hand_over_mouth": "hand over mouth",
	"shushing": "shushing",
	"symbols_over_mouth": "symbols over mouth",
	"exploding_head": "exploding head",
	"flushed": "flushed",
	"disappointed": "disappointed",
	"worried": "worried",
	"angry": "angry",
	"rage": "rage",
	"pensive": "pensive",
	"confused": "confused",
	"slightly_frowning_face": "slightly frowning face",
	"frowning_face": "frowning face",
	"persevere": "persevere",
	"confounded": "confounded",
	"tired_face": "tired face",
	"weary": "weary",
	"pleading": "pleading",
	"triumph": "triumph",
	"open_mouth": "open mouth",
	"scream": "scream",
	"fearful": "fearful",
	"cold_sweat": "cold sweat",
	"hushed": "hushed",
	"frowning": "frowning",
	"anguished": "anguished",
	"cry": "cry",
	"disappointed_relieved": "disappointed relieved",
	"drooling_face": "drooling face",
	"sleepy": "sleepy",
	"sweat": "sweat",
	"hot": "hot",
	"cold": "cold",
	"sob": "sob",
	"dizzy_face": "dizzy face",
	"astonished": "astonished",
	"zipper_mouth_face": "zipper mouth face",
	"nauseated_face": "nauseated face",
	"sneezing_face": "sneezing face",
	"vomiting": "vomiting",
	"mask": "mask",
	"face_with_thermometer": "face with thermometer",
	"face_with_head_bandage": "face with head bandage",
	"woozy": "woozy",
	"sleeping": "sleeping",
	"zzz": "zzz",
	"poop": "poop",
	"smiling_imp": "smiling imp",
	"imp": "imp",
	"japanese_ogre": "japanese ogre",
	"japanese_goblin": "japanese goblin",
	"skull": "skull",
	"ghost": "ghost",
	"alien": "alien",
	"robot": "robot",
	"smiley_cat": "smiley cat",
	"smile_cat": "smile cat",
	"joy_cat": "joy cat",
	"heart_eyes_cat": "heart eyes cat",
	"smirk_cat": "smirk cat",
	"kissing_cat": "kissing cat",
	"scream_cat": "scream cat",
	"crying_cat_face": "crying cat face",
	"pouting_cat": "pouting cat",
	"palms_up": "palms up",
	"raised_hands": "raised hands",
	"clap": "clap",
	"wave": "wave",
	"call_me_hand": "call me hand",
	"_1": " 1",
	"facepunch": "facepunch",
	"fist": "fist",
	"fist_left": "fist left",
	"fist_right": "fist right",
	"v": "v",
	"ok_hand": "ok hand",
	"raised_hand": "raised hand",
	"raised_back_of_hand": "raised back of hand",
	"open_hands": "open hands",
	"muscle": "muscle",
	"pray": "pray",
	"foot": "foot",
	"leg": "leg",
	"handshake": "handshake",
	"point_up": "point up",
	"point_up_2": "point up 2",
	"point_down": "point down",
	"point_left": "point left",
	"point_right": "point right",
	"fu": "fu",
	"raised_hand_with_fingers_splayed": "raised hand with fingers splayed",
	"love_you": "love you",
	"metal": "metal",
	"crossed_fingers": "crossed fingers",
	"vulcan_salute": "vulcan salute",
	"writing_hand": "writing hand",
	"selfie": "selfie",
	"nail_care": "nail care",
	"lips": "lips",
	"tooth": "tooth",
	"tongue": "tongue",
	"ear": "ear",
	"nose": "nose",
	"eye": "eye",
	"eyes": "eyes",
	"brain": "brain",
	"bust_in_silhouette": "bust in silhouette",
	"busts_in_silhouette": "busts in silhouette",
	"speaking_head": "speaking head",
	"baby": "baby",
	"child": "child",
	"boy": "boy",
	"girl": "girl",
	"adult": "adult",
	"man": "man",
	"woman": "woman",
	"blonde_woman": "blonde woman",
	"blonde_man": "blonde man",
	"bearded_person": "bearded person",
	"older_adult": "older adult",
	"older_man": "older man",
	"older_woman": "older woman",
	"man_with_gua_pi_mao": "man with gua pi mao",
	"woman_with_headscarf": "woman with headscarf",
	"woman_with_turban": "woman with turban",
	"man_with_turban": "man with turban",
	"policewoman": "policewoman",
	"policeman": "policeman",
	"construction_worker_woman": "construction worker woman",
	"construction_worker_man": "construction worker man",
	"guardswoman": "guardswoman",
	"guardsman": "guardsman",
	"female_detective": "female detective",
	"male_detective": "male detective",
	"woman_health_worker": "woman health worker",
	"man_health_worker": "man health worker",
	"woman_farmer": "woman farmer",
	"man_farmer": "man farmer",
	"woman_cook": "woman cook",
	"man_cook": "man cook",
	"woman_student": "woman student",
	"man_student": "man student",
	"woman_singer": "woman singer",
	"man_singer": "man singer",
	"woman_teacher": "woman teacher",
	"man_teacher": "man teacher",
	"woman_factory_worker": "woman factory worker",
	"man_factory_worker": "man factory worker",
	"woman_technologist": "woman technologist",
	"man_technologist": "man technologist",
	"woman_office_worker": "woman office worker",
	"man_office_worker": "man office worker",
	"woman_mechanic": "woman mechanic",
	"man_mechanic": "man mechanic",
	"woman_scientist": "woman scientist",
	"man_scientist": "man scientist",
	"woman_artist": "woman artist",
	"man_artist": "man artist",
	"woman_firefighter": "woman firefighter",
	"man_firefighter": "man firefighter",
	"woman_pilot": "woman pilot",
	"man_pilot": "man pilot",
	"woman_astronaut": "woman astronaut",
	"man_astronaut": "man astronaut",
	"woman_judge": "woman judge",
	"man_judge": "man judge",
	"woman_superhero": "woman superhero",
	"man_superhero": "man superhero",
	"woman_supervillain": "woman supervillain",
	"man_supervillain": "man supervillain",
	"mrs_claus": "mrs claus",
	"santa": "santa",
	"sorceress": "sorceress",
	"wizard": "wizard",
	"woman_elf": "woman elf",
	"man_elf": "man elf",
	"woman_vampire": "woman vampire",
	"man_vampire": "man vampire",
	"woman_zombie": "woman zombie",
	"man_zombie": "man zombie",
	"woman_genie": "woman genie",
	"man_genie": "man genie",
	"mermaid": "mermaid",
	"merman": "merman",
	"woman_fairy": "woman fairy",
	"man_fairy": "man fairy",
	"angel": "angel",
	"pregnant_woman": "pregnant woman",
	"breastfeeding": "breastfeeding",
	"princess": "princess",
	"prince": "prince",
	"bride_with_veil": "bride with veil",
	"man_in_tuxedo": "man in tuxedo",
	"running_woman": "running woman",
	"running_man": "running man",
	"walking_woman": "walking woman",
	"walking_man": "walking man",
	"dancer": "dancer",
	"man_dancing": "man dancing",
	"dancing_women": "dancing women",
	"dancing_men": "dancing men",
	"couple": "couple",
	"two_men_holding_hands": "two men holding hands",
	"two_women_holding_hands": "two women holding hands",
	"bowing_woman": "bowing woman",
	"bowing_man": "bowing man",
	"man_facepalming": "man facepalming",
	"woman_facepalming": "woman facepalming",
	"woman_shrugging": "woman shrugging",
	"man_shrugging": "man shrugging",
	"tipping_hand_woman": "tipping hand woman",
	"tipping_hand_man": "tipping hand man",
	"no_good_woman": "no good woman",
	"no_good_man": "no good man",
	"ok_woman": "ok woman",
	"ok_man": "ok man",
	"raising_hand_woman": "raising hand woman",
	"raising_hand_man": "raising hand man",
	"pouting_woman": "pouting woman",
	"pouting_man": "pouting man",
	"frowning_woman": "frowning woman",
	"frowning_man": "frowning man",
	"haircut_woman": "haircut woman",
	"haircut_man": "haircut man",
	"massage_woman": "massage woman",
	"massage_man": "massage man",
	"woman_in_steamy_room": "woman in steamy room",
	"man_in_steamy_room": "man in steamy room",
	"couple_with_heart_woman_man": "couple with heart woman man",
	"couple_with_heart_woman_woman": "couple with heart woman woman",
	"couple_with_heart_man_man": "couple with heart man man",
	"couplekiss_man_woman": "couplekiss man woman",
	"couplekiss_woman_woman": "couplekiss woman woman",
	"couplekiss_man_man": "couplekiss man man",
	"family_man_woman_boy": "family man woman boy",
	"family_man_woman_girl": "family man woman girl",
	"family_man_woman_girl_boy": "family man woman girl boy",
	"family_man_woman_boy_boy": "family man woman boy boy",
	"family_man_woman_girl_girl": "family man woman girl girl",
	"family_woman_woman_boy": "family woman woman boy",
	"family_woman_woman_girl": "family woman woman girl",
	"family_woman_woman_girl_boy": "family woman woman girl boy",
	"family_woman_woman_boy_boy": "family woman woman boy boy",
	"family_woman_woman_girl_girl": "family woman woman girl girl",
	"family_man_man_boy": "family man man boy",
	"family_man_man_girl": "family man man girl",
	"family_man_man_girl_boy": "family man man girl boy",
	"family_man_man_boy_boy": "family man man boy boy",
	"family_man_man_girl_girl": "family man man girl girl",
	"family_woman_boy": "family woman boy",
	"family_woman_girl": "family woman girl",
	"family_woman_girl_boy": "family woman girl boy",
	"family_woman_boy_boy": "family woman boy boy",
	"family_woman_girl_girl": "family woman girl girl",
	"family_man_boy": "family man boy",
	"family_man_girl": "family man girl",
	"family_man_girl_boy": "family man girl boy",
	"family_man_boy_boy": "family man boy boy",
	"family_man_girl_girl": "family man girl girl",
	"yarn": "yarn",
	"thread": "thread",
	"coat": "coat",
	"labcoat": "labcoat",
	"womans_clothes": "womans clothes",
	"tshirt": "tshirt",
	"jeans": "jeans",
	"necktie": "necktie",
	"dress": "dress",
	"bikini": "bikini",
	"kimono": "kimono",
	"lipstick": "lipstick",
	"kiss": "kiss",
	"footprints": "footprints",
	"flat_shoe": "flat shoe",
	"high_heel": "high heel",
	"sandal": "sandal",
	"boot": "boot",
	"mans_shoe": "mans shoe",
	"athletic_shoe": "athletic shoe",
	"hiking_boot": "hiking boot",
	"socks": "socks",
	"gloves": "gloves",
	"scarf": "scarf",
	"womans_hat": "womans hat",
	"tophat": "tophat",
	"billed_hat": "billed hat",
	"rescue_worker_helmet": "rescue worker helmet",
	"mortar_board": "mortar board",
	"crown": "crown",
	"school_satchel": "school satchel",
	"luggage": "luggage",
	"pouch": "pouch",
	"purse": "purse",
	"handbag": "handbag",
	"briefcase": "briefcase",
	"eyeglasses": "eyeglasses",
	"dark_sunglasses": "dark sunglasses",
	"goggles": "goggles",
	"ring": "ring",
	"closed_umbrella": "closed umbrella",

	// Животные и природа
	"dog": "dog",
	"cat": "cat",
	"mouse": "mouse",
	"hamster": "hamster",
	"rabbit": "rabbit",
	"fox_face": "fox face",
	"bear": "bear",
	"panda_face": "panda face",
	"koala": "koala",
	"tiger": "tiger",
	"lion": "lion",
	"cow": "cow",
	"pig": "pig",
	"pig_nose": "pig nose",
	"frog": "frog",
	"squid": "squid",
	"octopus": "octopus",
	"shrimp": "shrimp",
	"monkey_face": "monkey face",
	"gorilla": "gorilla",
	"see_no_evil": "see no evil",
	"hear_no_evil": "hear no evil",
	"speak_no_evil": "speak no evil",
	"monkey": "monkey",
	"chicken": "chicken",
	"penguin": "penguin",
	"bird": "bird",
	"baby_chick": "baby chick",
	"hatching_chick": "hatching chick",
	"hatched_chick": "hatched chick",
	"duck": "duck",
	"eagle": "eagle",
	"owl": "owl",
	"bat": "bat",
	"wolf": "wolf",
	"boar": "boar",
	"horse": "horse",
	"unicorn": "unicorn",
	"honeybee": "honeybee",
	"bug": "bug",
	"butterfly": "butterfly",
	"snail": "snail",
	"beetle": "beetle",
	"ant": "ant",
	"grasshopper": "grasshopper",
	"spider": "spider",
	"scorpion": "scorpion",
	"crab": "crab",
	"snake": "snake",
	"lizard": "lizard",
	"t_rex": "t rex",
	"sauropod": "sauropod",
	"turtle": "turtle",
	"tropical_fish": "tropical fish",
	"fish": "fish",
	"blowfish": "blowfish",
	"dolphin": "dolphin",
	"shark": "shark",
	"whale": "whale",
	"whale2": "whale2",
	"crocodile": "crocodile",
	"leopard": "leopard",
	"zebra": "zebra",
	"tiger2": "tiger2",
	"water_buffalo": "water buffalo",
	"ox": "ox",
	"cow2": "cow2",
	"deer": "deer",
	"dromedary_camel": "dromedary camel",
	"camel": "camel",
	"giraffe": "giraffe",
	"elephant": "elephant",
	"rhinoceros": "rhinoceros",
	"goat": "goat",
	"ram": "ram",
	"sheep": "sheep",
	"racehorse": "racehorse",
	"pig2": "pig2",
	"rat": "rat",
	"mouse2": "mouse2",
	"rooster": "rooster",
	"turkey": "turkey",
	"dove": "dove",
	"dog2": "dog2",
	"poodle": "poodle",
	"cat2": "cat2",
	"rabbit2": "rabbit2",
	"chipmunk": "chipmunk",
	"hedgehog": "hedgehog",
	"raccoon": "raccoon",
	"llama": "llama",
	"hippopotamus": "hippopotamus",
	"kangaroo": "kangaroo",
	"badger": "badger",
	"swan": "swan",
	"peacock": "peacock",
	"parrot": "parrot",
	"lobster": "lobster",
	"mosquito": "mosquito",
	"paw_prints": "paw prints",
	"dragon": "dragon",
	"dragon_face": "dragon face",
	"cactus": "cactus",
	"christmas_tree": "christmas tree",
	"evergreen_tree": "evergreen tree",
	"deciduous_tree": "deciduous tree",
	"palm_tree": "palm tree",
	"seedling": "seedling",
	"herb": "herb",
	"shamrock": "shamrock",
	"four_leaf_clover": "four leaf clover",
	"bamboo": "bamboo",
	"tanabata_tree": "tanabata tree",
	"leaves": "leaves",
	"fallen_leaf": "fallen leaf",
	"maple_leaf": "maple leaf",
	"ear_of_rice": "ear of rice",
	"hibiscus": "hibiscus",
	"sunflower": "sunflower",
	"rose": "rose",
	"wilted_flower": "wilted flower",
	"tulip": "tulip",
	"blossom": "blossom",
	"cherry_blossom": "cherry blossom",
	"bouquet": "bouquet",
	"mushroom": "mushroom",
	"chestnut": "chestnut",
	"jack_o_lantern": "jack o lantern",
	"shell": "shell",
	"spider_web": "spider web",
	"earth_americas": "earth americas",
	"earth_africa": "earth africa",
	"earth_asia": "earth asia",
	"full_moon": "full moon",
	"waning_gibbous_moon": "waning gibbous moon",
	"last_quarter_moon": "last quarter moon",
	"waning_crescent_moon": "waning crescent moon",
	"new_moon": "new moon",
	"waxing_crescent_moon": "waxing crescent moon",
	"first_quarter_moon": "first quarter moon",
	"waxing_gibbous_moon": "waxing gibbous moon",
	"new_moon_with_face": "new moon with face",
	"full_moon_with_face": "full moon with face",
	"first_quarter_moon_with_face": "first quarter moon with face",
	"last_quarter_moon_with_face": "last quarter moon with face",
	"sun_with_face": "sun with face",
	"crescent_moon": "crescent moon",
	"star": "star",
	"star2": "star2",
	"dizzy": "dizzy",
	"sparkles": "sparkles",
	"comet": "comet",
	"sunny": "sunny",
	"sun_behind_small_cloud": "sun behind small cloud",
	"partly_sunny": "partly sunny",
	"sun_behind_large_cloud": "sun behind large cloud",
	"sun_behind_rain_cloud": "sun behind rain cloud",
	"cloud": "cloud",
	"cloud_with_rain": "cloud with rain",
	"cloud_with_lightning_and_rain": "cloud with lightning and rain",
	"cloud_with_lightning": "cloud with lightning",
	"zap": "zap",
	"fire": "fire",
	"boom": "boom",
	"snowflake": "snowflake",
	"cloud_with_snow": "cloud with snow",
	"snowman": "snowman",
	"snowman_with_snow": "snowman with snow",
	"wind_face": "wind face",
	"dash": "dash",
	"tornado": "tornado",
	"fog": "fog",
	"open_umbrella": "open umbrella",
	"umbrella": "umbrella",
	"droplet": "droplet",
	"sweat_drops": "sweat drops",
	"ocean": "ocean",

	// Еда и напитки
	"green_apple": "green apple",
	"apple": "apple",
	"pear": "pear",
	"tangerine": "tangerine",
	"lemon": "lemon",
	"banana": "banana",
	"watermelon": "watermelon",
	"grapes": "grapes",
	"strawberry": "strawberry",
	"melon": "melon",
	"cherries": "cherries",
	"peach": "peach",
	"pineapple": "pineapple",
	"coconut": "coconut",
	"kiwi_fruit": "kiwi fruit",
	"mango": "mango",
	"avocado": "avocado",
	"broccoli": "broccoli",
	"tomato": "tomato",
	"eggplant": "eggplant",
	"cucumber": "cucumber",
	"carrot": "carrot",
	"hot_pepper": "hot pepper",
	"potato": "potato",
	"corn": "corn",
	"leafy_greens": "leafy greens",
	"sweet_potato": "sweet potato",
	"peanuts": "peanuts",
	"honey_pot": "honey pot",
	"croissant": "croissant",
	"bread": "bread",
	"baguette_bread": "baguette bread",
	"bagel": "bagel",
	"pretzel": "pretzel",
	"cheese": "cheese",
	"egg": "egg",
	"bacon": "bacon",
	"steak": "steak",
	"pancakes": "pancakes",
	"poultry_leg": "poultry leg",
	"meat_on_bone": "meat on bone",
	"bone": "bone",
	"fried_shrimp": "fried shrimp",
	"fried_egg": "fried egg",
	"hamburger": "hamburger",
	"fries": "fries",
	"stuffed_flatbread": "stuffed flatbread",
	"hotdog": "hotdog",
	"pizza": "pizza",
	"sandwich": "sandwich",
	"canned_food": "canned food",
	"spaghetti": "spaghetti",
	"taco": "taco",
	"burrito": "burrito",
	"green_salad": "green salad",
	"shallow_pan_of_food": "shallow pan of food",
	"ramen": "ramen",
	"stew": "stew",
	"fish_cake": "fish cake",
	"fortune_cookie": "fortune cookie",
	"sushi": "sushi",
	"bento": "bento",
	"curry": "curry",
	"rice_ball": "rice ball",
	"rice": "rice",
	"rice_cracker": "rice cracker",
	"oden": "oden",
	"dango": "dango",
	"shaved_ice": "shaved ice",
	"ice_cream": "ice cream",
	"icecream": "icecream",
	"pie": "pie",
	"cake": "cake",
	"cupcake": "cupcake",
	"moon_cake": "moon cake",
	"birthday": "birthday",
	"custard": "custard",
	"candy": "candy",
	"lollipop": "lollipop",
	"chocolate_bar": "chocolate bar",
	"popcorn": "popcorn",
	"dumpling": "dumpling",
	"doughnut": "doughnut",
	"cookie": "cookie",
	"milk_glass": "milk glass",
	"beer": "beer",
	"beers": "beers",
	"clinking_glasses": "clinking glasses",
	"wine_glass": "wine glass",
	"tumbler_glass": "tumbler glass",
	"cocktail": "cocktail",
	"tropical_drink": "tropical drink",
	"champagne": "champagne",
	"sake": "sake",
	"tea": "tea",
	"cup_with_straw": "cup with straw",
	"coffee": "coffee",
	"baby_bottle": "baby bottle",
	"salt": "salt",
	"spoon": "spoon",
	"fork_and_knife": "fork and knife",
	"plate_with_cutlery": "plate with cutlery",
	"bowl_with_spoon": "bowl with spoon",
	"takeout_box": "takeout box",
	"chopsticks": "chopsticks",

	// Деятельность
	"soccer": "soccer",
	"basketball": "basketball",
	"football": "football",
	"baseball": "baseball",
	"softball": "softball",
	"tennis": "tennis",
	"volleyball": "volleyball",
	"rugby_football": "rugby football",
	"flying_disc": "flying disc",
	"8ball": "8ball",
	"golf": "golf",
	"golfing_woman": "golfing woman",
	"golfing_man": "golfing man",
	"ping_pong": "ping pong",
	"badminton": "badminton",
	"goal_net": "goal net",
	"ice_hockey": "ice hockey",
	"field_hockey": "field hockey",
	"lacrosse": "lacrosse",
	"cricket": "cricket",
	"ski": "ski",
	"skier": "skier",
	"snowboarder": "snowboarder",
	"person_fencing": "person fencing",
	"women_wrestling": "women wrestling",
	"men_wrestling": "men wrestling",
	"woman_cartwheeling": "woman cartwheeling",
	"man_cartwheeling": "man cartwheeling",
	"woman_playing_handball": "woman playing handball",
	"man_playing_handball": "man playing handball",
	"ice_skate": "ice skate",
	"curling_stone": "curling stone",
	"skateboard": "skateboard",
	"sled": "sled",
	"bow_and_arrow": "bow and arrow",
	"fishing_pole_and_fish": "fishing pole and fish",
	"boxing_glove": "boxing glove",
	"martial_arts_uniform": "martial arts uniform",
	"rowing_woman": "rowing woman",
	"rowing_man": "rowing man",
	"climbing_woman": "climbing woman",
	"climbing_man": "climbing man",
	"swimming_woman": "swimming woman",
	"swimming_man": "swimming man",
	"woman_playing_water_polo": "woman playing water polo",
	"man_playing_water_polo": "man playing water polo",
	"woman_in_lotus_position": "woman in lotus position",
	"man_in_lotus_position": "man in lotus position",
	"surfing_woman": "surfing woman",
	"surfing_man": "surfing man",
	"bath": "bath",
	"basketball_woman": "basketball woman",
	"basketball_man": "basketball man",
	"weight_lifting_woman": "weight lifting woman",
	"weight_lifting_man": "weight lifting man",
	"biking_woman": "biking woman",
	"biking_man": "biking man",
	"mountain_biking_woman": "mountain biking woman",
	"mountain_biking_man": "mountain biking man",
	"horse_racing": "horse racing",
	"business_suit_levitating": "business suit levitating",
	"trophy": "trophy",
	"running_shirt_with_sash": "running shirt with sash",
	"medal_sports": "medal sports",
	"medal_military": "medal military",
	"1st_place_medal": "1st place medal",
	"2nd_place_medal": "2nd place medal",
	"3rd_place_medal": "3rd place medal",
	"reminder_ribbon": "reminder ribbon",
	"rosette": "rosette",
	"ticket": "ticket",
	"tickets": "tickets",
	"performing_arts": "performing arts",
	"art": "art",
	"circus_tent": "circus tent",
	"woman_juggling": "woman juggling",
	"man_juggling": "man juggling",
	"microphone": "microphone",
	"headphones": "headphones",
	"musical_score": "musical score",
	"musical_keyboard": "musical keyboard",
	"drum": "drum",
	"saxophone": "saxophone",
	"trumpet": "trumpet",
	"guitar": "guitar",
	"violin": "violin",
	"clapper": "clapper",
	"video_game": "video game",
	"space_invader": "space invader",
	"dart": "dart",
	"game_die": "game die",
	"chess_pawn": "chess pawn",
	"slot_machine": "slot machine",
	"jigsaw": "jigsaw",
	"bowling": "bowling",

	// Путешествия и места
	"red_car": "red car",
	"taxi": "taxi",
	"blue_car": "blue car",
	"bus": "bus",
	"trolleybus": "trolleybus",
	"racing_car": "racing car",
	"police_car": "police car",
	"ambulance": "ambulance",
	"fire_engine": "fire engine",
	"minibus": "minibus",
	"truck": "truck",
	"articulated_lorry": "articulated lorry",
	"tractor": "tractor",
	"kick_scooter": "kick scooter",
	"motorcycle": "motorcycle",
	"bike": "bike",
	"motor_scooter": "motor scooter",
	"rotating_light": "rotating light",
	"oncoming_police_car": "oncoming police car",
	"oncoming_bus": "oncoming bus",
	"oncoming_automobile": "oncoming automobile",
	"oncoming_taxi": "oncoming taxi",
	"aerial_tramway": "aerial tramway",
	"mountain_cableway": "mountain cableway",
	"suspension_railway": "suspension railway",
	"railway_car": "railway car",
	"train": "train",
	"monorail": "monorail",
	"bullettrain_side": "bullettrain side",
	"bullettrain_front": "bullettrain front",
	"light_rail": "light rail",
	"mountain_railway": "mountain railway",
	"steam_locomotive": "steam locomotive",
	"train2": "train2",
	"metro": "metro",
	"tram": "tram",
	"station": "station",
	"flying_saucer": "flying saucer",
	"helicopter": "helicopter",
	"small_airplane": "small airplane",
	"airplane": "airplane",
	"flight_departure": "flight departure",
	"flight_arrival": "flight arrival",
	"sailboat": "sailboat",
	"motor_boat": "motor boat",
	"speedboat": "speedboat",
	"ferry": "ferry",
	"passenger_ship": "passenger ship",
	"rocket": "rocket",
	"artificial_satellite": "artificial satellite",
	"seat": "seat",
	"canoe": "canoe",
	"construction": "construction",
	"fuelpump": "fuelpump",
	"busstop": "busstop",
	"vertical_traffic_light": "vertical traffic light",
	"traffic_light": "traffic light",
	"checkered_flag": "checkered flag",
	"ship": "ship",
	"ferris_wheel": "ferris wheel",
	"roller_coaster": "roller coaster",
	"carousel_horse": "carousel horse",
	"building_construction": "building construction",
	"foggy": "foggy",
	"tokyo_tower": "tokyo tower",
	"factory": "factory",
	"fountain": "fountain",
	"rice_scene": "rice scene",
	"mountain": "mountain",
	"mountain_snow": "mountain snow",
	"mount_fuji": "mount fuji",
	"volcano": "volcano",
	"japan": "japan",
	"camping": "camping",
	"tent": "tent",
	"national_park": "national park",
	"motorway": "motorway",
	"railway_track": "railway track",
	"sunrise": "sunrise",
	"sunrise_over_mountains": "sunrise over mountains",
	"desert": "desert",
	"beach_umbrella": "beach umbrella",
	"desert_island": "desert island",
	"city_sunrise": "city sunrise",
	"city_sunset": "city sunset",
	"cityscape": "cityscape",
	"night_with_stars": "night with stars",
	"bridge_at_night": "bridge at night",
	"milky_way": "milky way",
	"stars": "stars",
	"sparkler": "sparkler",
	"fireworks": "fireworks",
	"rainbow": "rainbow",
	"houses": "houses",
	"european_castle": "european castle",
	"japanese_castle": "japanese castle",
	"stadium": "stadium",
	"statue_of_liberty": "statue of liberty",
	"house": "house",
	"house_with_garden": "house with garden",
	"derelict_house": "derelict house",
	"office": "office",
	"department_store": "department store",
	"post_office": "post office",
	"european_post_office": "european post office",
	"hospital": "hospital",
	"bank": "bank",
	"hotel": "hotel",
	"convenience_store": "convenience store",
	"school": "school",
	"love_hotel": "love hotel",
	"wedding": "wedding",
	"classical_building": "classical building",
	"church": "church",
	"mosque": "mosque",
	"synagogue": "synagogue",
	"kaaba": "kaaba",
	"shinto_shrine": "shinto shrine",

	// Объекты
	"watch": "watch",
	"iphone": "iphone",
	"calling": "calling",
	"computer": "computer",
	"keyboard": "keyboard",
	"desktop_computer": "desktop computer",
	"printer": "printer",
	"computer_mouse": "computer mouse",
	"trackball": "trackball",
	"joystick": "joystick",
	"clamp": "clamp",
	"minidisc": "minidisc",
	"floppy_disk": "floppy disk",
	"cd": "cd",
	"dvd": "dvd",
	"vhs": "vhs",
	"camera": "camera",
	"camera_flash": "camera flash",
	"video_camera": "video camera",
	"movie_camera": "movie camera",
	"film_projector": "film projector",
	"film_strip": "film strip",
	"telephone_receiver": "telephone receiver",
	"phone": "phone",
	"pager": "pager",
	"fax": "fax",
	"tv": "tv",
	"radio": "radio",
	"studio_microphone": "studio microphone",
	"level_slider": "level slider",
	"control_knobs": "control knobs",
	"compass": "compass",
	"stopwatch": "stopwatch",
	"timer_clock": "timer clock",
	"alarm_clock": "alarm clock",
	"mantelpiece_clock": "mantelpiece clock",
	"hourglass_flowing_sand": "hourglass flowing sand",
	"hourglass": "hourglass",
	"satellite": "satellite",
	"battery": "battery",
	"electric_plug": "electric plug",
	"bulb": "bulb",
	"flashlight": "flashlight",
	"candle": "candle",
	"fire_extinguisher": "fire extinguisher",
	"wastebasket": "wastebasket",
	"oil_drum": "oil drum",
	"money_with_wings": "money with wings",
	"dollar": "dollar",
	"yen": "yen",
	"euro": "euro",
	"pound": "pound",
	"moneybag": "moneybag",
	"credit_card": "credit card",
	"gem": "gem",
	"balance_scale": "balance scale",
	"toolbox": "toolbox",
	"wrench": "wrench",
	"hammer": "hammer",
	"hammer_and_pick": "hammer and pick",
	"hammer_and_wrench": "hammer and wrench",
	"pick": "pick",
	"nut_and_bolt": "nut and bolt",
	"gear": "gear",
	"brick": "brick",
	"chains": "chains",
	"magnet": "magnet",
	"gun": "gun",
	"bomb": "bomb",
	"firecracker": "firecracker",
	"hocho": "hocho",
	"dagger": "dagger",
	"crossed_swords": "crossed swords",
	"shield": "shield",
	"smoking": "smoking",
	"skull_and_crossbones": "skull and crossbones",
	"coffin": "coffin",
	"funeral_urn": "funeral urn",
	"amphora": "amphora",
	"crystal_ball": "crystal ball",
	"prayer_beads": "prayer beads",
	"nazar_amulet": "nazar amulet",
	"barber": "barber",
	"alembic": "alembic",
	"telescope": "telescope",
	"microscope": "microscope",
	"hole": "hole",
	"pill": "pill",
	"syringe": "syringe",
	"dna": "dna",
	"microbe": "microbe",
	"petri_dish": "petri dish",
	"test_tube": "test tube",
	"thermometer": "thermometer",
	"broom": "broom",
	"basket": "basket",
	"toilet_paper": "toilet paper",
	"label": "label",
	"bookmark": "bookmark",
	"toilet": "toilet",
	"shower": "shower",
	"bathtub": "bathtub",
	"soap": "soap",
	"sponge": "sponge",
	"lotion_bottle": "lotion bottle",
	"key": "key",
	"old_key": "old key",
	"couch_and_lamp": "couch and lamp",
	"sleeping_bed": "sleeping bed",
	"bed": "bed",
	"door": "door",
	"bellhop_bell": "bellhop bell",
	"teddy_bear": "teddy bear",
	"framed_picture": "framed picture",
	"world_map": "world map",
	"parasol_on_ground": "parasol on ground",
	"moyai": "moyai",
	"shopping": "shopping",
	"shopping_cart": "shopping cart",
	"balloon": "balloon",
	"ribbon": "ribbon",
	"gift": "gift",
	"confetti_ball": "confetti ball",
	"tada": "tada",
	"dolls": "dolls",
	"wind_chime": "wind chime",
	"crossed_flags": "crossed flags",
	"izakaya_lantern": "izakaya lantern",
	"red_envelope": "red envelope",
	"email": "email",
	"envelope_with_arrow": "envelope with arrow",
	"incoming_envelope": "incoming envelope",
	"e_mail": "e mail",
	"love_letter": "love letter",
	"postbox": "postbox",
	"mailbox_closed": "mailbox closed",
	"mailbox": "mailbox",
	"mailbox_with_mail": "mailbox with mail",
	"mailbox_with_no_mail": "mailbox with no mail",
	"package": "package",
	"postal_horn": "postal horn",
	"inbox_tray": "inbox tray",
	"outbox_tray": "outbox tray",
	"scroll": "scroll",
	"page_with_curl": "page with curl",
	"bookmark_tabs": "bookmark tabs",
	"receipt": "receipt",
	"bar_chart": "bar chart",
	"chart_with_upwards_trend": "chart with upwards trend",
	"chart_with_downwards_trend": "chart with downwards trend",
	"page_facing_up": "page facing up",
	"date": "date",
	"calendar": "calendar",
	"spiral_calendar": "spiral calendar",
	"card_index": "card index",
	"card_file_box": "card file box",
	"ballot_box": "ballot box",
	"file_cabinet": "file cabinet",
	"clipboard": "clipboard",
	"spiral_notepad": "spiral notepad",
	"file_folder": "file folder",
	"open_file_folder": "open file folder",
	"card_index_dividers": "card index dividers",
	"newspaper_roll": "newspaper roll",
	"newspaper": "newspaper",
	"notebook": "notebook",
	"closed_book": "closed book",
	"green_book": "green book",
	"blue_book": "blue book",
	"orange_book": "orange book",
	"notebook_with_decorative_cover": "notebook with decorative cover",
	"ledger": "ledger",
	"books": "books",
	"open_book": "open book",
	"safety_pin": "safety pin",
	"paperclip": "paperclip",
	"paperclips": "paperclips",
	"scissors": "scissors",
	"triangular_ruler": "triangular ruler",
	"straight_ruler": "straight ruler",
	"abacus": "abacus",
	"pushpin": "pushpin",
	"round_pushpin": "round pushpin",
	"triangular_flag_on_post": "triangular flag on post",
	"white_flag": "white flag",
	"black_flag": "black flag",
	"rainbow_flag": "rainbow flag",
	"closed_lock_with_key": "closed lock with key",
	"lock": "lock",
	"unlock": "unlock",
	"lock_with_ink_pen": "lock with ink pen",
	"pen": "pen",
	"fountain_pen": "fountain pen",
	"black_nib": "black nib",
	"memo": "memo",
	"pencil2": "pencil2",
	"crayon": "crayon",
	"paintbrush": "paintbrush",
	"mag": "mag",
	"mag_right": "mag right",

	// Флаги
	"afghanistan": "afghanistan",
	"aland_islands": "aland islands",
	"albania": "albania",
	"algeria": "algeria",
	"american_samoa": "american samoa",
	"andorra": "andorra",
	"angola": "angola",
	"anguilla": "anguilla",
	"antarctica": "antarctica",
	"antigua_barbuda": "antigua barbuda",
	"argentina": "argentina",
	"armenia": "armenia",
	"aruba": "aruba",
	"australia": "australia",
	"austria": "austria",
	"azerbaijan": "azerbaijan",
	"bahamas": "bahamas",
	"bahrain": "bahrain",
	"bangladesh": "bangladesh",
	"barbados": "barbados",
	"belarus": "belarus",
	"belgium": "belgium",
	"belize": "belize",
	"benin": "benin",
	"bermuda": "bermuda",
	"bhutan": "bhutan",
	"bolivia": "bolivia",
	"caribbean_netherlands": "caribbean netherlands",
	"bosnia_herzegovina": "bosnia herzegovina",
	"botswana": "botswana",
	"brazil": "brazil",
	"british_indian_ocean_territory": "british indian ocean territory",
	"british_virgin_islands": "british virgin islands",
	"brunei": "brunei",
	"bulgaria": "bulgaria",
	"burkina_faso": "burkina faso",
	"burundi": "burundi",
	"cape_verde": "cape verde",
	"cambodia": "cambodia",
	"cameroon": "cameroon",
	"canada": "canada",
	"canary_islands": "canary islands",
	"cayman_islands": "cayman islands",
	"central_african_republic": "central african republic",
	"chad": "chad",
	"chile": "chile",
	"cn": "cn",
	"christmas_island": "christmas island",
	"cocos_islands": "cocos islands",
	"colombia": "colombia",
	"comoros": "comoros",
	"congo_brazzaville": "congo brazzaville",
	"congo_kinshasa": "congo kinshasa",
	"cook_islands": "cook islands",
	"costa_rica": "costa rica",
	"croatia": "croatia",
	"cuba": "cuba",
	"curacao": "curacao",
	"cyprus": "cyprus",
	"czech_republic": "czech republic",
	"denmark": "denmark",
	"djibouti": "djibouti",
	"dominica": "dominica",
	"dominican_republic": "dominican republic",
	"ecuador": "ecuador",
	"egypt": "egypt",
	"el_salvador": "el salvador",
	"equatorial_guinea": "equatorial guinea",
	"eritrea": "eritrea",
	"estonia": "estonia",
	"ethiopia": "ethiopia",
	"eu": "eu",
	"falkland_islands": "falkland islands",
	"faroe_islands": "faroe islands",
	"fiji": "fiji",
	"finland": "finland",
	"fr": "fr",
	"french_guiana": "french guiana",
	"french_polynesia": "french polynesia",
	"french_southern_territories": "french southern territories",
	"gabon": "gabon",
	"gambia": "gambia",
	"georgia": "georgia",
	"de": "de",
	"ghana": "ghana",
	"gibraltar": "gibraltar",
	"greece": "greece",
	"greenland": "greenland",
	"grenada": "grenada",
	"guadeloupe": "guadeloupe",
	"guam": "guam",
	"guatemala": "guatemala",
	"guernsey": "guernsey",
	"guinea": "guinea",
	"guinea_bissau": "guinea bissau",
	"guyana": "guyana",
	"haiti": "haiti",
	"honduras": "honduras",
	"hong_kong": "hong kong",
	"hungary": "hungary",
	"iceland": "iceland",
	"india": "india",
	"indonesia": "indonesia",
	"iran": "iran",
	"iraq": "iraq",
	"ireland": "ireland",
	"isle_of_man": "isle of man",
	"israel": "israel",
	"it": "it",
	"cote_divoire": "cote divoire",
	"jamaica": "jamaica",
	"jp": "jp",
	"jersey": "jersey",
	"jordan": "jordan",
	"kazakhstan": "kazakhstan",
	"kenya": "kenya",
	"kiribati": "kiribati",
	"kosovo": "kosovo",
	"kuwait": "kuwait",
	"kyrgyzstan": "kyrgyzstan",
	"laos": "laos",
	"latvia": "latvia",
	"lebanon": "lebanon",
	"lesotho": "lesotho",
	"liberia": "liberia",
	"libya": "libya",
	"liechtenstein": "liechtenstein",
	"lithuania": "lithuania",
	"luxembourg": "luxembourg",
	"macau": "macau",
	"macedonia": "macedonia",
	"madagascar": "madagascar",
	"malawi": "malawi",
	"malaysia": "malaysia",
	"maldives": "maldives",
	"mali": "mali",
	"malta": "malta",
	"marshall_islands": "marshall islands",
	"martinique": "martinique",
	"mauritania": "mauritania",
	"mauritius": "mauritius",
	"mayotte": "mayotte",
	"mexico": "mexico",
	"micronesia": "micronesia",
	"moldova": "moldova",
	"monaco": "monaco",
	"mongolia": "mongolia",
	"montenegro": "montenegro",
	"montserrat": "montserrat",
	"morocco": "morocco",
	"mozambique": "mozambique",
	"myanmar": "myanmar",
	"namibia": "namibia",
	"nauru": "nauru",
	"nepal": "nepal",
	"netherlands": "netherlands",
	"new_caledonia": "new caledonia",
	"new_zealand": "new zealand",
	"nicaragua": "nicaragua",
	"niger": "niger",
	"nigeria": "nigeria",
	"niue": "niue",
	"norfolk_island": "norfolk island",
	"northern_mariana_islands": "northern mariana islands",
	"north_korea": "north korea",
	"norway": "norway",
	"oman": "oman",
	"pakistan": "pakistan",
	"palau": "palau",
	"palestinian_territories": "palestinian territories",
	"panama": "panama",
	"papua_new_guinea": "papua new guinea",
	"paraguay": "paraguay",
	"peru": "peru",
	"philippines": "philippines",
	"pitcairn_islands": "pitcairn islands",
	"poland": "poland",
	"portugal": "portugal",
	"puerto_rico": "puerto rico",
	"qatar": "qatar",
	"reunion": "reunion",
	"romania": "romania",
	"ru": "ru",
	"rwanda": "rwanda",
	"st_barthelemy": "st barthelemy",
	"st_helena": "st helena",
	"st_kitts_nevis": "st kitts nevis",
	"st_lucia": "st lucia",
	"st_pierre_miquelon": "st pierre miquelon",
	"st_vincent_grenadines": "st vincent grenadines",
	"samoa": "samoa",
	"san_marino": "san marino",
	"sao_tome_principe": "sao tome principe",
	"saudi_arabia": "saudi arabia",
	"senegal": "senegal",
	"serbia": "serbia",
	"seychelles": "seychelles",
	"sierra_leone": "sierra leone",
	"singapore": "singapore",
	"sint_maarten": "sint maarten",
	"slovakia": "slovakia",
	"slovenia": "slovenia",
	"solomon_islands": "solomon islands",
	"somalia": "somalia",
	"south_africa": "south africa",
	"south_georgia_south_sandwich_islands": "south georgia south sandwich islands",
	"kr": "kr",
	"south_sudan": "south sudan",
	"es": "es",
	"sri_lanka": "sri lanka",
	"sudan": "sudan",
	"suriname": "suriname",
	"swaziland": "swaziland",
	"sweden": "sweden",
	"switzerland": "switzerland",
	"syria": "syria",
	"taiwan": "taiwan",
	"tajikistan": "tajikistan",
	"tanzania": "tanzania",
	"thailand": "thailand",
	"timor_leste": "timor leste",
	"togo": "togo",
	"tokelau": "tokelau",
	"tonga": "tonga",
	"trinidad_tobago": "trinidad tobago",
	"tunisia": "tunisia",
	"tr": "tr",
	"turkmenistan": "turkmenistan",
	"turks_caicos_islands": "turks caicos islands",
	"tuvalu": "tuvalu",
	"uganda": "uganda",
	"ukraine": "ukraine",
	"united_arab_emirates": "united arab emirates",
	"uk": "uk",
	"england": "england",
	"scotland": "scotland",
	"wales": "wales",
	"us": "us",
	"us_virgin_islands": "us virgin islands",
	"uruguay": "uruguay",
	"uzbekistan": "uzbekistan",
	"vanuatu": "vanuatu",
	"vatican_city": "vatican city",
	"venezuela": "venezuela",
	"vietnam": "vietnam",
	"wallis_futuna": "wallis futuna",
	"western_sahara": "western sahara",
	"yemen": "yemen",
	"zambia": "zambia",
	"zimbabwe": "zimbabwe",
	"united_nations": "united nations",
	"pirate_flag": "pirate flag",
});
